---
title: "Case Study: Covid19 Analysis"
author: "Binod"
date: "5/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

raw_covid19_confirmed <- read_csv("data/raw_covid19_confirmed.csv", col_types = cols())
raw_covid19_deaths <- read_csv("data/raw_covid19_deaths.csv", col_types = cols())
raw_covid19_recovered <- read_csv("data/raw_covid19_recovered.csv", col_types = cols())
```

```{r}
confirmed <- pivot_longer(raw_covid19_confirmed,
cols = 5:ncol(raw_covid19_confirmed),
names_to = "confirmed",
values_to = "count"
) %>%
janitor::clean_names() %>%
filter(country_region = "Nepal")

deaths <- pivot_longer(raw_covid19_deaths ,
cols = 5:ncol(raw_covid19_deaths ),
names_to = "deaths",
values_to = "count"
) %>%
janitor::clean_names() %>%
filter(country_region == "Nepal")


recovered <- pivot_longer(raw_covid19_recovered,
cols = 5:ncol(raw_covid19_recovered),
names_to = "recovered",
values_to = "count"
) %>%
janitor::clean_names() %>%
filter(country_region == "Nepal")

```

```{r}
covid19_nepal <- confirmed %>%
left_join(deaths) %>%
left_join(recovered)
```

```{r}
covid19_nepal <- covid19_nepal %>%
mutate(date = mdy(date)) 
```

```{r eval = F}

covid19_nepal %>%
ggplot(aes(x = date, y = confirmed)) +
geom_line()
```

```{r}
covid19_nepal %>%
ggplot(aes(x = date, y = confirmed)) +
  geom_line()

covid19_nepal_viz <-  covid19_nepal %>%
pivot_longer(
  cols = c("confirmed", "deaths", "recovered"),
  names_to = "cases",
  values_to = "count"
)
```


```{r}
covid19_nepal_viz %>%
ggplot(aes(x = date, y = count, color = cases)) +
geom_line()
glimpse(covid19_nepal_viz)
```

```{r}
covid19_nepal_viz %>%
group_by(cases) %>%
mutate(daily_count = count - lag(count, default = 0))
```

```{r}
covid19_daily_nepal <- covid19_nepal_viz %>%
group_by(cases) %>%
mutate(daily_count = count - lag(count, default = 0))
```

```{r}
covid19_daily_nepal <- covid19_nepal_viz %>%
group_by(cases) %>%
mutate(daily_count = count - lag(count, default = 0, order_by = date))
```

```{r}
covid19_daily_nepal %>%
ggplot(aes(x = date, y = daily_count, color = cases)) +
geom_line()
```

```{r}
covid19_daily_nepal %>%
ggplot(aes(x = date, y = daily_count, color = cases)) +
geom_line()
```

```{r}
covid19_daily_nepal %>%
ggplot( aes(x = date, y = daily_count, color = cases)) +
geom_line() +
labs(title = "Covid19-Nepal Cases") +
theme_minimal()
```

```{r}
confirmed <- pivot_longer(raw_covid19_confirmed,
cols = 5:ncol(raw_covid19_confirmed),
names_to = "date",
values_to = "confirmed"
) %>%
janitor::clean_names() %>%
filter(country_region == "Nepal")
```

```{r}
covid19_nepal_viz <-  covid19_nepal %>%
pivot_longer(
cols = c("confirmed", "deaths", "recovered"),
names_to = "cases",
values_to = "count"
)
```

```{r}
covid19_daily_nepal <- covid19_nepal_viz %>%
  group_by(cases) %>%
  mutate(daily_count = count - lag(count, default = 0, order_by = date))
```


>  daily_count = cumulative_count - previous_cum_count


```{r}

covid19_daily_nepal %>%
ggplot( aes(x = date, y = daily_count, color = cases)) +
geom_line() +
labs(title = "Covid19-Nepal Cases") +
theme_minimal()
```

