---
title: "Untitled"
author: "SanjayHamal"
date: "6/9/2021"
output: html_document
---
```{r}
library(DBI)
library(odbc)

#con <- dbConnect(odbc(),
    #             Driver = "SQL Server",
     #            Server = "SANJAY\\SQLEXPRESS ",
     #            Database = "UNIVERSITY",
                 #UID = "",
                 #PWD = rstudioapi::askForPassword("Database password")
                 #Port = 0)
```

```{r}

sort(unique(odbcListDrivers()[[1]]))
```

```{r}
con <- dbConnect(odbc(), 
                 Driver = "SQL Server", 
                 Server = "SANJAY\\SQLEXPRESS", 
                 Database = "UNIVERSITY", 
                 Trusted_Connection = "True")


dbListTables(con)

```

```{r}
#Reading table from con:

df1<- DBI::dbReadTable(con, 'water_analysis')

#Reading table using dbGetQuery:
df2<- DBI::dbGetQuery(con, "SELECT * FROM water_analysis")
df2

#To write to the database:
DBI::dbWriteTable(con, "water_analysis2", df1)
```


```{r}
con2<- odbc::dbConnect(odbc(), 
                       Driver= "SQL Server",
                       Server= "SANJAY\\SQLEXpress",
                       Database= "DB123",
                       Trusted_Connection=T
                 
                       
                       )

summary(con2)
con
con2
?odbc

DBI::dbWriteTable(con2, "water_analysis2", df1)
DBI::dbRemoveTable(con, "water_analysis2")
```

```{r}
dbListTables(con2)

#To get column names from db table:

dbListFields(con2, "water_analysis2")
```
```{r}


#dbReadTable reads the whole table.

dbReadTable(con2, 'water_analysis2')


#limit number of rows to read by writing sql query:

dbGetQuery(con2, "select top 20 [Samples], [TH_final] from water_analysis2")

#fetch data in batches:[few rows at a time]

some_query<- dbSendQuery(con2, "select [Samples], [TH_final] from water_analysis2")


for (i in seq(5)){
  
  print(dbFetch(some_query, 4))
  
}


#to know the query status: T/F
DBI::dbHasCompleted(some_query)

#to get info about query:
 DBI::dbGetInfo(some_query)
 
#get latest query:
 dbGetStatement(some_query)
 
#get row count from query:
 dbGetRowCount(some_query)
 
#get info about rows added or deleted:
 dbGetRowsAffected(some_query)
 
#For column info:
 dbColumnInfo(some_query)
 
#to free memory:
 
dbClearResult(some_query)
 some_query
 
#To check if some table exists in db. 
dbExistsTable(con2, 'water_analysis2')


```
```{r}

dfx<-data.frame(val1 = c('a', 'b', 'c'), val2= c(1, 2, 3), val3= c('p', 'q', 'r'))
dfx

DBI::dbWriteTable(con2, "dfx", dfx)

g=DBI::dbGetQuery(con2, "select * from dfx")

# Now to override the contents of dfx in database:
library(tidyverse)

g<- g %>% mutate(val3= 'override values')
g

DBI::dbWriteTable(con2, 'dfx', g, overwrite=T)


DBI::dbGetQuery(con2, "Select * from dfx")
```
```{r}
##appending rows in the database:

dfx_2<- data.frame(val1=letters[10:12], val2=seq(4, 6), val3=LETTERS[14:16])
dfx_2

DBI::dbWriteTable(con2, 'dfx', dfx_2, append=T)


```


```{r}
#applying above concepts:


rows_100<- data.frame(col1= c(1:100))
rows_100

DBI::dbWriteTable(con2, 'rows_100', rows_100)

DBI::dbGetQuery(con2, "select *from rows_100")

q1<- DBI::dbSendQuery(con2, "select * from rows_100")

DBI::dbFetch(q1, 40)

dbClearResult(q1)
```


```{r}
g= ceiling(121/40)
g

q2= DBI::dbGetQuery(con2, "select count(*) from rows_100 as cnts")
q2
to_send= DBI::dbSendQuery(con2,"Select [col1] from rows_100")
to_send
for (i in seq(ceiling(q2[1,1]/30))){
  temp_table <- DBI::dbFetch(to_send, 30)
  temp_table<- temp_table %>% mutate(col2= col1+1)
  task1=DBI::dbWriteTable(con2, 'rows_100', temp_table, append=T)
  
}
temp_table
seq(ceiling(q2[1,1]/30))

DBI::dbGetQuery(con2, 'select * from rows_100')
```

```{r}
#to get statements:

DBI::dbReadTable(con2, 'dfx')

dfx3<- data.frame(val1='e', val2=4, val3='new_val')


h= DBI::sqlAppendTable(con2, 'dfx', dfx3)
h


```
```{sql connection=con2}


 select [val1] from dfx
```


